### ISSUE TITLE
Secciones

### ISSUE THREAD

**Issue by jarquinlesman** [UNICAH-ICC-SAP/GestionPracticasApi#10]
Este módulo garantizará que las secciones no choquen con otras del mismo bloque, con la posibilidad de excepciones para clases generales, y alertará en caso de problemas.

Las clases tendrán la siguiente nomenclatura con respecto al tipo de clase:

- 1 --> Clase normal.
- 2 --> Inglés
- 3 --> Labotarotorio.
- 4 --> Coprogramáticas

Requisitos:
- Registro de secciones por bloque.
- Evaluación de horarios para evitar conflictos.

Validaciones:
- Las secciones no deben chocar con otra sección del mismo bloque, salvo excepciones evaluadas.

Notificaciones y advertencias:
- Advertencias en caso de conflictos horarias.

**Comment by jarquinlesman** [comment]
Necesito que base de datos modifique en la tabla de clases, el campo llamado es_lab para que se convierta en tipo_clase, de está manera será conveniente la validación de secciones por clase y evitar que choquen en horarios.

Dicho campo deberá ser de tipo int, y seguirá la siguiente nomenclatura:
1 --> Clase normal
2 --> Inglés
3 --> Laboratorio
4 --> Coprogramatica

Así se podrán hacer las validaciones y evitar choques de horarios al momento de asignar las respectivas secciones a cada clase.

**Comment by LuisF20** [comment]
Se ha realizado el cambio solicitado para la tabla "clases".

**Comment by jarquinlesman** [comment]
Agregar a la tabla de detalle_periodo hora_final para poder determinar y manejar los casos de las secciones en horario especial.

**Comment by LuisF20** [comment]
Se ha realizado el cambio correspondiente en la BD.

**Comment by jarquinlesman** [comment]
Se subió el pr con el las rutas y el controller de secciones que contiene los siguiente endpoint:

1. Insertar una nueva sección (insert).
2. Editar una sección existente (update).
3. Eliminar una sección existente (deleteSection).

Cabe destacar que se agregaron todas las validaciones necesarias y que se establecieron para evitar choques de horarios con las clases y con los docentes.

También se agregaron los modelos de periodo y detalle_periodo.

**Comment by nixiagonzalez06** [comment]
Se agregó la creación, modificación y eliminación de las secciones en los pénsum, laboratorios y coprogramáticas.
