### ISSUE TITLE
Login

### ISSUE THREAD

**Issue by jarquinlesman** [UNICAH-ICC-SAP/GestionPracticasApi#13]
Este módulo se encargará de autenticar a los usuarios administradores del sistema, docentes y alumnos, asegurando que solo los usuarios autorizados puedan acceder al sistema.

Requisitos:
- Obtener datos de usuario y contraseña del administrador, docente y alumno.

Validaciones:
- Verificar la validez de las credenciales ingresadas.

Notificaciones y advertencias:
- Notificar al usuario si las credenciales son incorrectas.

**Comment by jarquinlesman** [comment]
Se agregó el endpoint llamado resetPasword que recibe el userId en el query y la newPassword del body para actualizar la nueva contraseña. Además, se actualiza el campo de passwordResetRequired a false para que ya no pida cambio de contraseña.

De igual forma, ya se creo el pr.

**Comment by jarquinlesman** [comment]
Se hizo el push con el cambio solicitado para que en el método SignIn muestre el campo de passwordResetRequired y así determinar si se le debe obligar al usuario a cambiar su contraseña.

**Comment by BryanHHZavala** [comment]
se creo un pr del login que contiene lo siguiente:

1. modales:
se añadieron 2 modales, la primera es para  dar un mensaje al usuario para que sepa que tiene que cambiar la contraseña, la segunda modal es para cambiar la contraseña.

2. cambios visuales:
se hicieron pequeños cambios visuales en el login, y se agrego un boton para poder ver la contraseña

3. modificacion en el App.tsx:
se hicieron unos cambio en el app ya que este generaba un bug al iniciar sesión, cuando se iniciaba sesion no mostraba las modales porque desde la app.tsx se mandaba a la navigation, ahora la cuadno se inicia sesion se verifica que si el campo resetPasswordRequired es true se quede en el login y muestra las modales para poder cambiar la contraseña

4. slices:
se modifico el namespace con campos necesarios para poder hacer el cambio de contraseña, asi mismo se agregaron los fetcher, selectores y reducers

5. beadcrumbs:
en el beadcrumb se agrego un padding-top de 3px

**Comment by BryanHHZavala** [comment]
se modifico el type de breadcrumb para seguir el estandar del proyecto
