### ISSUE TITLE
Periodos

### ISSUE THREAD

**Issue by Kevin504Hn** [UNICAH-ICC-SAP/GestionPracticasApi#19]
Los períodos académicos serán registrados y gestionados como un historial, permitiendo un seguimiento claro de las clases ofrecidas.

Requisitos:
- Registro de cada período académico.

**Comment by Kevin504Hn** [comment]
Se desarrollaron el controlador, el modelo y la ruta para gestionar los periodos. En el controlador se implementaron las funciones de inserción y consulta, destinadas a crear nuevos periodos y recuperar información de los existentes.

**Comment by jazlq1** [comment]
Se creó un PR en el que se implementó un nuevo componente de NuevaCarga que permite crear un nuevo periodo ingresando las fechas tanto de inicio como de final (implementando ciertas funciones como formatDate), y también seleccionando un periodo específico.  En esta parte también se aplicó un estilo personalizado para mejorar la presentación del formulario. 
También se creó el slice de "periodo" y la acción "InsertNuevaCarga" para poder gestionar las operaciones que están relacionadas con periodo y poder mandar los datos al backend.
