### ISSUE TITLE
Correo

### ISSUE THREAD

**Issue by DarponJoscas** [UNICAH-ICC-SAP/GestionPracticasApi#26]
Este módulo se encargará de enviar las credenciales (usuario y contraseña) a los usuarios por correo, facilitando el acceso al sistema.

Requisitos:
- Funcionalidad para enviar correos electrónicos.

**Comment by BryanHHZavala** [comment]
el correo tiene lo siguiente:

1. se crearon el modelo para el correo que tendra el id del correo, el asunto y el cuerpo

2. se creo el controller con los siguientes metodos http:
- post: se creo un metodo para agregar diferentes plantillas de correo para sus diferente usos, para la creacion de un docente o alumno

-put: se creo un modulo para actualizar plantillas mediante el id 

-post: se realizo un modulo para poder enviar un correo mediante una plantilla especifica

get: modulo para obtener todas las plantillas

4. se crearon las diferentes rutas para cada controller

**Comment by DarponJoscas** [comment]
Las extensiones que se usaron para poder enviar el correo y que el sistema tenga seguridad contra inyecciones sql son:

- nodemailer
- he
