### ISSUE TITLE
Docentes

### ISSUE THREAD

**Issue by jarquinlesman** [UNICAH-ICC-SAP/GestionPracticasApi#5]
La carga académica de cada docente debe ser visible mediante un filtro, permitiendo gestionar y visualizar las asignaciones de clases sin conflictos de horario.

Requisitos:
- Mostrar la carga académica de cada docente. (Se realizará en el módulo de cargas).
- Filtrar docentes activos.
- Mostrar las clases de un docente en particular. (Se realizará en el módulo de cargas).

Validaciones:
- Las horas de cada clase asignada a cada docente no deben chocar con otras. (Se realizará en el módulo de cargas).

Notificaciones y advertencias:
- Advertencias si hay conflictos en la carga horaria de los docentes. (Se realizará en el módulo de cargas).

**Comment by jarquinlesman** [comment]
Crear el estado del docente, para que al momento de poder eliminarlo, lo único que se haga es poder desactivarlo de la vista del administrador, pero no de la base de datos.

**Comment by LuisF20** [comment]
Cambios realizados en la base de datos GestionPracticas:

1. Se agregó la columna "passwordResetRequired" en la tabla "users" para poder permitir el restablecimiento de la contraseña del usuario.
2. Se  creó la tabla "estadoTerna" relacionandola con la tabla "detalle_terna", para colocar el estado de la respectiva terna.
3. Se agregó la columna "estadoDocente" en la tabla "docente" para activar o inactivar al mismo.

**Comment by jarquinlesman** [comment]
Cambios realizados en el archivo de **backend** de docenteController.js y en docenteRoutes.js:

1. Se modificó el método de **update** para que el parámetro del docente a actualizar sea enviado como query y no como parámetro de la URL.
2. Se agregó la función **updateStatus** para que al momento de querer eliminar docente, este únicamente se desactive en la base de datos, es decir, cambie su estado de 1 a 0.
3. Se modificó la ruta de **update** para que ya no mandará los parámetros por URL sino mediante el query.
4. Se agregó la ruta de **updateStatus** para poder desactivar al docente.

**Comment by LuisF20** [comment]
Cambios realizados en la base de datos GestionPracticas:

1.  Se hizo un cambio en la extensión del campo "Telefono" en las tablas "Alumno" y "Docente", pasando de varchar(9) a varchar(15).

**Comment by BryanHHZavala** [comment]
cambios en el front:
1. se crearon los metodos de CRUD en docentes
2. se instalo una dependencia Sweetalert2 para notificaciones al usuario
