### ISSUE TITLE
Administracion

### ISSUE THREAD

**Issue by Bryan1129** [UNICAH-ICC-SAP/GestionPracticasApi#8]
Módulo Administrativo:
Creacion y guardado de las ternas, creacion del alumno y su usuario y lectura final de todo lo que complementa la terna.

Observaciones:

Para crear terna se necesita del alumno, docente y facultades.
La terna tendra un estado de inactivo al crearse.
En el apartado web estara la vista para modificar, la de crear que ya existe y la que ocupamos trabajar seria el mostrado de la terna, es decir lectura de ternas.

**Comment by Bryan1129** [comment]
Cambios en el api de alumnos, ternas, y usuarios. Se trabajo en los modelos de los 3 apartados y en los controladores de los 3 apartados.

**Comment by Bryan1129** [comment]
Seguimos en progreso, para la creacion de las ternas, pronto haremos nuevas actualizaciones.

**Comment by Acalix-unicah** [comment]
Favor retroalimentación sobre el estado de la actividad en la parte del front.

@YosselinMolina

**Comment by Bryan1129** [comment]
1. Creacion de Ternas Funcional:

- En el resumen de la creacion de terna agregamos toda la funcionalidad correspondiente al creado, se crea el usuario del alumno, el alumno, la terna y el detalle de la terna.
- Logramos tambien mejorar en el step 1 la parte del correo, ya que no lo tomaba el @unicah.edu, y eso era una problematica en el guardado.

2. sub Menu:

- En el subMenu solo ordenamos el orden de cada una de las pestañas, y se dejo como primera pestaña la creacion de ternas, las otras dos las trabajaran los encargados de modificar la terna y el alumno, asi que solo se movio a la primera pestaña la de crear ternas.

3. Store Alumnos:

- Se cambio todo el store, ya que estaba basado en facultades y eso generaba problemas, entonces lo trabajamos cada apartado para que redireccione bien toda la informacion del alumno.
- En el caso del fetcher, los cambiamos de fetcher facultades a alumnos, y agregamos los saveDataAlumno y el updateAlumno para el actualizado de la informacion del alumno y mejoramos el getAlumnos y el getAlumno
- En el namespace, cambiamos el nombre de facultades a alumno y se cambio el nombre de storeFacultades a storeAlumnos, la informacion del alumno no se modifico.
- En el reducer agregamos dos nuevos case que es el de saveDataAlumno, y el case de updateAlumnos y actualizamos los nombres de las acciones, ya que el reducer tenia basada la mayoria de acciones en facultades, y lo corregimos ya que ahora se basan en alumnos.
- En el selector tambien lo corregimos, ya que estaba basado en facultades y lo actualizamos a alumnos, los selectores se quedaron de la misma manera, ya que la informacion se maneja de manera correcta.
- En el index, solo cambios el nombre del store, ya que se llamaba StoreFacultad, y lo cambiamos a StoreAlumnos, asi manejamos de manera correcta todo el store de alumnos.

4. Store Ternas:

- Agregamos en el fetcher unas nuevas mejoras para el funcionamiento de ternas, agregamos el saveTernas, y el saveDetalleTernas, para el guardado de las ternas y el detalle.
- En el reducer solo agregamos los case para cada una de las nuevas funcionalidades, que en este caso era el saveTernas y el saveDetalleTernas, tambien cambiamos una accion de userCreate, ya que creaba las contraseñas de manera ramdon, y no como se establecia en el resumen.
- En el selector de ternas, solo agregamos algunos selectores que requeriamos en el resumen, pero como tal no se hizo mucho cambio.

5. Store Users:
- Agregamos en el fetcher de Users, el singUp, para la creacion del usuario del alumno, asi al mandar a llamar este proceso en el resumen, creabamos el usuario de manera correcta.
- En el reducer agregamos el case para el singUp, asi llevamos actualizado cada mejora y cambio que realizamos.
